### ISSUE TITLE
Support true and false as schemas

### ISSUE THREAD

**Issue by jnthn** [croservices/json-schema#4]
Per [the spec](https://json-schema.org/latest/json-schema-core.html#rfc.section.4.3.1):

> A JSON Schema MUST be an object or a boolean.
> ...
> The boolean schema values "true" and "false" are trivial assertions that always return themselves regardless of the instance value. As an example, in terms of the validation vocabulary, boolean schemas are equivalent to the following behaviors:
> 
> true:
> Always passes validation, as if the empty schema {}
> false:
> Always fails validation, as if the schema { "not":{} }

We currently don't implement this, but should to do, to enable `additionalProperties: false` to work, for example.

**Comment by Altai-man** [comment]
Urgent or not?

**Comment by jnthn** [comment]
This week would be good.
